language: c
group: travis_latest
dist: xenial

# safelist
branches:
  only:
  - master
  - develop

# blocklist
branches:
  except:
  - jupyter-tutorials

before_install:
  - sudo add-apt-repository ppa:octave/stable -y
  - sudo apt-get update -q
  - sudo apt-get install octave liboctave-dev python-pip -y
  - pip install --upgrade pip
  - pip install --user jupyter
  - pip install --user octave_kernel
  
addons:
  apt:
    packages:
    - octave
    - liboctave-dev
    - gcc
    - g++

matrix:
  include:
  - os: linux
  
script:
- gcc --version
- octave-cli --version
- octave-cli install_octave.m
- cd doc && ./notebooks_to_html.sh

