language: c
group: travis_latest
dist: xenial

before_install:
  - sudo add-apt-repository ppa:octave/stable -y
  - sudo apt-get update -q
  
addons:
  apt:
    packages:
    - octave
    - liboctave-dev
    - gcc
    - g++

matrix:
  include:
  - os: linux
  
script:
- gcc --version
- octave-cli --version
- octave-cli install_octave.m
